---

- name: distribution specific languages
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - fallback.yml
  tags:
    - always

- debug: msg={{ vbox.pkg_mgr }}
  tags:
    - debug

- name: VirtualBox package
  package:
    name: virtualbox
    state: present
    use: "{{ vbox.pkg_mgr|default(ansible_pkg_mgr) }}"
